### ISSUE TITLE
Project architecture does not follow the best practice

### ISSUE THREAD

**Issue by karam-mustafa** [Syrian-Open-Source/Hotel-Management-System#11]
I recommend separating the project parties into repositories for each folder
so we can see like this: 
for the backend, create a new repo called "hoter-management-system-backend"
for the frontend, create a new repo called "hoter-management-system-frontend"
for the mobile, create a new repo called "hoter-management-system-mobile"
and so on ..., these repositories basically helps us to develop requirements better and also helps to organize the work of developers more
Because sometimes it is possible only for frontend developers to work on the front part and backend developers develop the backend part and so on.

Thanks for you're heart work !!

**Comment by somarkn99** [comment]
Thanks for the issue.

The information I put forward has been taken into account.

the project is separated into 3 different repositories you can check it out from:

1. https://github.com/Syrian-Open-Source/Hotel-Management-System-frontend
2. https://github.com/Syrian-Open-Source/Hotel-Management-System--mobile
