### ISSUE TITLE
Validation best bractice

### ISSUE THREAD

**Issue by karam-mustafa** [Syrian-Open-Source/Hotel-Management-System#12]
* You should use a validation class for each request that requires the validation part, just like the UserRequest class 
* Every request class should extend a base class called BaseRequest, and this base class should have all duplicated functions like `failedValidation()` and failure functions to handle the validation error response
* I think it is better to handle the error messages through the translation file in case you do not have any private message you want to return

**Comment by somarkn99** [comment]
For the second part of this issue, it is solved in the last commit you can check it out if you want.
